const Constants = {
  FETCHED_POKEMONS: 'FETCHED_POKEMONS',
  FILTER_POKEMONS: 'FILTER_POKEMONS',
  FETCH_POKEMON: 'FETCH_POKEMON',
  CLEAR_POKEMONS: 'CLEAR_POKEMONS',
  START_FETCHING: 'START_FETCHING',
  SUCCESS_FETCHING: 'SUCCESS_FETCHING',
  CANCEL_FETCHING: 'CANCEL_FETCHING',
  REGION: 'REGION',
  HABITAT: 'HABITAT',
  GENDER: 'GENDER',
};

export default Constants;
