const Constants = {
  FETCHED_POKEMONS: 'FETCHED_POKEMONS',
  FETCH_POKEMON: 'FETCH_POKEMON',
  SET_POKEMON: 'SET_POKEMON',
  START_FETCHING: 'START_FETCHING',
  SUCCESS_FETCHING: 'SUCCESS_FETCHING',
  CANCEL_FETCHING: 'CANCEL_FETCHING',
  SET_FILTER: 'SET_FILTER',
  DISPLAY_ITEM: 'DISPLAY_ITEM',
};

export default Constants;
