const Constants = {
  FETCHED_POKEMONS: 'FETCHED_POKEMONS',
  FETCHED_POKEMON: 'FETCHED_POKEMON',
  START_FETCHING: 'START_FETCHING',
  CANCEL_FETCHING: 'CANCEL_FETCHING',
  SET_FILTER: 'SET_FILTER',
};

export default Constants;
